name: test
on:
  push:
    branches:
      - 2.13.x
  pull_request:
jobs:
  test:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: coursier/cache-action@v6
    - uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 8
    - name: Test
      # This runs the template with the default parameters, and runs test within the templated app.
      run: sbt -Dfile.encoding=UTF8 test
